<?php
function getDropdownState(){
	$st=["SELECT STATE","ANDHRA PRADESH","ARUNACHAL PRADESH","ASAM","BIHAR","CHHATTISGARH","GUJARAT","GOA","	
	HARIYANA","HIMACHAL PRADESH","JHARKHAND","KERALA","MAHARASHTRA","ODISHA","RAJASTHAN","	
	TAMIL NADU","UTTAR PRADESH","WEST BENGAL"];
	return $st;
}
?>